#!/usr/bin/env bash
set -euo pipefail

# TASK: Dockerfile auto-generation foundation — actual Docker CLI build.
# The test is opt-in because it pulls the pinned nginx base image and requires
# a local Docker daemon. Normal `go test ./...` remains daemon-independent.
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "${ROOT_DIR}/apps/runner"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required for this e2e" >&2
  exit 1
fi
docker info >/dev/null

RUNNER_AUTO_DOCKERFILE_E2E=1 go test ./internal/docker \
  -run '^TestAutoGenerated(DockerfileCliBuild|NodeDockerfileCliBuildIsReproducible)$' -count=1 -v
