apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dib-hosted-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dib-hosted-app.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dib-hosted-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dib-hosted-app.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_BASE_PATH
              value: {{ .Values.hosting.basePath | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
