{{- if .Values.hosting.tier }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "dib-hosted-app.fullname" . }}-quota
  labels:
    app.kubernetes.io/name: {{ include "dib-hosted-app.name" . }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
    pods: {{ .Values.quota.pods | quote }}
{{- end }}
