export const DEFAULT_PREVIEW_TTL_MINUTES = 60;
export const DEFAULT_RUNNER_POLL_INTERVAL_MS = 5000;
export const DEFAULT_BUILD_TIMEOUT_SECONDS = 900;
export const DEFAULT_BUILD_REPOSITORY_BACKEND = "memory";
