package docker

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/ykylee/docker-image-builder-system/apps/runner/internal/dockerfile"
)

func TestAutoGeneratedDockerfileCliBuild(t *testing.T) {
	if os.Getenv("RUNNER_AUTO_DOCKERFILE_E2E") != "1" {
		t.Skip("set RUNNER_AUTO_DOCKERFILE_E2E=1 to run the Docker CLI e2e")
	}

	buildID := "auto-dockerfile-e2e"
	workspace := t.TempDir()
	sourceDir := filepath.Join(workspace, "src")
	if err := os.MkdirAll(sourceDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sourceDir, "index.html"), []byte("<h1>auto</h1>\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	generated, err := dockerfile.Ensure(sourceDir, "Dockerfile", dockerfile.ModeAuto)
	if err != nil {
		t.Fatal(err)
	}
	if !generated.Generated || generated.Template != "static-nginx" {
		t.Fatalf("unexpected generation result: %+v", generated)
	}

	t.Setenv("RUNNER_DOCKER_BUILD_MODE", "cli")
	t.Setenv("RUNNER_WORKSPACE_ROOT", workspace)
	client := NewClient()
	tag := client.ImageTagFor(buildID)
	t.Cleanup(func() {
		_ = exec.Command("docker", "image", "rm", "-f", tag).Run()
	})

	if err := client.BuildImage(context.Background(), buildID, sourceDir, "Dockerfile"); err != nil {
		t.Fatal(err)
	}

	manifestBytes, err := os.ReadFile(filepath.Join(workspace, buildID, "build-manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	var manifest buildManifest
	if err := json.Unmarshal(manifestBytes, &manifest); err != nil {
		t.Fatal(err)
	}
	if !manifest.DockerfileGenerated || manifest.DockerfileTemplate != "static-nginx" {
		t.Fatalf("manifest lost Dockerfile provenance: %+v", manifest)
	}
}

func TestAutoGeneratedNodeDockerfileCliBuildIsReproducible(t *testing.T) {
	if os.Getenv("RUNNER_AUTO_DOCKERFILE_E2E") != "1" {
		t.Skip("set RUNNER_AUTO_DOCKERFILE_E2E=1 to run the Docker CLI e2e")
	}

	workspace := t.TempDir()
	sourceDir := filepath.Join(workspace, "src")
	if err := os.MkdirAll(sourceDir, 0o755); err != nil {
		t.Fatal(err)
	}
	packageJSON := `{"name":"auto-node-e2e","version":"1.0.0","scripts":{"start":"node server.js"}}` + "\n"
	if err := os.WriteFile(filepath.Join(sourceDir, "package.json"), []byte(packageJSON), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sourceDir, "server.js"), []byte("console.log('auto-node');\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	generated, err := dockerfile.Ensure(sourceDir, "Dockerfile", dockerfile.ModeAuto)
	if err != nil {
		t.Fatal(err)
	}
	if generated.Template != "node" {
		t.Fatalf("unexpected generation result: %+v", generated)
	}

	t.Setenv("RUNNER_DOCKER_BUILD_MODE", "cli")
	t.Setenv("RUNNER_WORKSPACE_ROOT", workspace)
	client := NewClient()
	ids := []string{"auto-node-e2e-a", "auto-node-e2e-b"}
	t.Cleanup(func() {
		for _, id := range ids {
			_ = exec.Command("docker", "image", "rm", "-f", client.ImageTagFor(id)).Run()
		}
	})

	imageIDs := make([]string, 0, len(ids))
	for _, id := range ids {
		if err := client.BuildImage(context.Background(), id, sourceDir, "Dockerfile"); err != nil {
			t.Fatal(err)
		}
		output, err := exec.Command("docker", "image", "inspect", "--format", "{{.Id}}", client.ImageTagFor(id)).Output()
		if err != nil {
			t.Fatal(err)
		}
		imageIDs = append(imageIDs, string(output))
	}
	if imageIDs[0] != imageIDs[1] {
		t.Fatalf("generated Node image is not reproducible: %q != %q", imageIDs[0], imageIDs[1])
	}
}
